from repositories.service_repository import ServiceRepository
from repositories.service_request_repository import ServiceRequestRepository
from repositories.uav_repository import UAVRepository
from repositories.uav_service_repository import UAVServiceRepository
