apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: service-handler-api-backendconfig
spec:
  timeoutSec: 900
  connectionDraining:
    drainingTimeoutSec: 120
---
apiVersion: v1
kind: Service
metadata:
  name: service-handler-api-service
  namespace: default
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    cloud.google.com/backend-config: '{"ports": {"3000":"service-handler-api-backendconfig"}}'
  labels:
    k8s-app: service-handler-api
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    k8s-app: service-handler-api